Percobaan Docker: 1
reacto11mecha/enpitsu pull request #31
Opened 2024-01-19 10:13 UTC by manoedinata

Ini adalah percobaan awal dari konfigurasi Docker untuk deploy Enpitsu (production) agar siap diakses dari luar dan untuk user yang cukup ramai.

#25

2024-01-19 14:13 UTC, reacto11mecha commented
Wokey, mantep

2024-01-21 01:03 UTC, reacto11mecha requested changes
Sedikit review, takut kelupaan

2024-01-21 01:03 UTC, reacto11mecha commented on docker-compose.yaml
> +      VITE_TRPC_URL: https://${ENPITSU_VIRTUAL_HOST}/api/trpc
```suggestion
```

Ini dihapus aja, ini aslinya cuman buat bagian web ulangannya

2024-01-21 01:08 UTC, manoedinata commented on docker-compose.yaml
> +      VITE_TRPC_URL: https://${ENPITSU_VIRTUAL_HOST}/api/trpc
Oke

2024-01-21 01:08 UTC, manoedinata commented
Jangan di merge dulu. Nanti akan di squash agar rapi.

2024-01-21 01:12 UTC, reacto11mecha commented
Iya, emang belum, tapi ada opsi squash merge di github

2024-01-21 01:15 UTC, manoedinata commented
Aku squash manual aja. Ada yg perlu diperbaiki juga. Ntar siang.

2024-01-21 01:17 UTC, reacto11mecha commented
Sip dah

2024-01-21 04:35 UTC, reacto11mecha approved these changes

2024-01-21 04:35 UTC, merged